{'name': 'root', 'msg': 'Erro de divis\xe3o por zero: division by zero', 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'C:\\Users\\alepj\\Desktop\\Back End - Chat GPT\\M\xeas 1 - Aprofundamento em Python\\Semana 1 - Revis\xe3o de Python Avan\xe7ado\\Dia 5 - Tratamento de erros e logging\\Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging.py', 'filename': 'Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging.py', 'module': 'Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 26, 'funcName': '<module>', 'created': 1739896744.4373205, 'msecs': 437.0, 'relativeCreated': 1516.0864, 'thread': 11180, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 6776, 'taskName': None, 'message': 'Erro de divis\xe3o por zero: division by zero'}sctime)s - ERROR - Erro de divisão por zero: division by zero
{'name': 'root', 'msg': "Erro de valor inv\xe1lido: invalid literal for int() with base 10: 'ABC'", 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'C:\\Users\\alepj\\Desktop\\Back End - Chat GPT\\M\xeas 1 - Aprofundamento em Python\\Semana 1 - Revis\xe3o de Python Avan\xe7ado\\Dia 5 - Tratamento de erros e logging\\Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging.py', 'filename': 'Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging.py', 'module': 'Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 23, 'funcName': '<module>', 'created': 1739896756.340539, 'msecs': 340.0, 'relativeCreated': 7374.891, 'thread': 8564, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 10208, 'taskName': None, 'message': "Erro de valor inv\xe1lido: invalid literal for int() with base 10: 'ABC'"}sctime)s - ERROR - Erro de valor inválido: invalid literal for int() with base 10: 'ABC'
{'name': 'root', 'msg': "Erro de valor inv\xe1lido: invalid literal for int() with base 10: 'ABC'", 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'C:\\Users\\alepj\\Desktop\\Back End - Chat GPT\\M\xeas 1 - Aprofundamento em Python\\Semana 1 - Revis\xe3o de Python Avan\xe7ado\\Dia 5 - Tratamento de erros e logging\\Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging.py', 'filename': 'Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging.py', 'module': 'Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 23, 'funcName': '<module>', 'created': 1739896762.9903424, 'msecs': 990.0, 'relativeCreated': 2037.3624, 'thread': 13256, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 9960, 'taskName': None, 'message': "Erro de valor inv\xe1lido: invalid literal for int() with base 10: 'ABC'"}sctime)s - ERROR - Erro de valor inválido: invalid literal for int() with base 10: 'ABC'
{'name': 'root', 'msg': 'Erro de divis\xe3o por zero: division by zero', 'args': (), 'levelname': 'ERROR', 'levelno': 40, 'pathname': 'C:\\Users\\alepj\\Desktop\\Back End - Chat GPT\\M\xeas 1 - Aprofundamento em Python\\Semana 1 - Revis\xe3o de Python Avan\xe7ado\\Dia 5 - Tratamento de erros e logging\\Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging.py', 'filename': 'Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging.py', 'module': 'Exerc\xedcio Pr\xe1tico 2 - Adicionando Logging', 'exc_info': None, 'exc_text': None, 'stack_info': None, 'lineno': 26, 'funcName': '<module>', 'created': 1739896767.603973, 'msecs': 603.0, 'relativeCreated': 693.1665, 'thread': 10928, 'threadName': 'MainThread', 'processName': 'MainProcess', 'process': 3292, 'taskName': None, 'message': 'Erro de divis\xe3o por zero: division by zero'}sctime)s - ERROR - Erro de divisão por zero: division by zero
2025-02-18 14:15:22,571 - WARNING - Tentativa de Login inválida: Usuário ou Senha incorretos.
2025-02-18 14:15:34,386 - WARNING - Tentativa de Login inválida: Usuário ou Senha incorretos.
2025-02-18 14:15:37,003 - WARNING - Tentativa de Login inválida: Usuário ou Senha incorretos.
2025-02-18 14:15:37,905 - WARNING - Tentativa de Login inválida: Usuário ou Senha incorretos.
2025-02-18 14:15:37,906 - ERROR - Usuário bloqueado após 3 tentativas.
